### ISSUE TITLE
Marking episodes watched quickly causes some not to be stored on server

### ISSUE THREAD

**Issue by kevnfu** [kevnfu/e-unibus-pluram#7]
Plan to fix this by keeping a local js ratings model and only sending to server periodically/when leaving page.

**Comment by kevnfu** [comment]
Pushed a new build to live server. Now all changes are stored locally, and synced with the server every 10 seconds (is this time reasonable @Paintgoo?). It also syncs when the user switches to another page, or closes the page. Should reduce data contention issue.

Leaving this issue open for a bit longer to see if any bugs pop up.

**Comment by paintgoo** [comment]
Yes, let's test it out like this for awhile and see if we run into any issues.

**Comment by kevnfu** [comment]
According to documentation as long as database writes are 1s apart, it should be fine. I changed it so it updates every 2 seconds. Still need to figure out what to do on mobile devices not connected to the internet.

**Comment by kevnfu** [comment]
Think it's been pretty robust. Closing now.
